// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package public

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	BADREQUEST        ErrorCode = "BAD_REQUEST"
	CONFLICT          ErrorCode = "CONFLICT"
	DUPLICATEDETECTED ErrorCode = "DUPLICATE_DETECTED"
	FILETOOLARGE      ErrorCode = "FILE_TOO_LARGE"
	INTERNALERROR     ErrorCode = "INTERNAL_ERROR"
	INVALIDEDIFACT    ErrorCode = "INVALID_EDIFACT"
	NOTFOUND          ErrorCode = "NOT_FOUND"
)

// Defines values for HealthChecksKafka.
const (
	HealthChecksKafkaError HealthChecksKafka = "error"
	HealthChecksKafkaOk    HealthChecksKafka = "ok"
)

// Defines values for HealthChecksPostgres.
const (
	HealthChecksPostgresError HealthChecksPostgres = "error"
	HealthChecksPostgresOk    HealthChecksPostgres = "ok"
)

// Defines values for HealthStatus.
const (
	Degraded  HealthStatus = "degraded"
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Defines values for IngestStatus.
const (
	IngestStatusCompleted IngestStatus = "completed"
	IngestStatusFailed    IngestStatus = "failed"
)

// Defines values for InterchangeDetailStatus.
const (
	InterchangeDetailStatusCompleted InterchangeDetailStatus = "completed"
	InterchangeDetailStatusFailed    InterchangeDetailStatus = "failed"
)

// Error defines model for error.
type Error struct {
	// Code Machine-readable error code
	Code ErrorCode `json:"code"`

	// CorrelationId X-Correlation-ID from request headers
	CorrelationId string `json:"correlation_id"`

	// Message Human-readable description
	Message string `json:"message"`
}

// ErrorCode Machine-readable error code
type ErrorCode string

// Health defines model for health.
type Health struct {
	Checks struct {
		Kafka    *HealthChecksKafka    `json:"kafka,omitempty"`
		Postgres *HealthChecksPostgres `json:"postgres,omitempty"`
	} `json:"checks"`
	Status HealthStatus `json:"status"`
}

// HealthChecksKafka defines model for Health.Checks.Kafka.
type HealthChecksKafka string

// HealthChecksPostgres defines model for Health.Checks.Postgres.
type HealthChecksPostgres string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ingest defines model for ingest.
type Ingest struct {
	// ErrorDetail Populated only when status = failed
	ErrorDetail    nullable.Nullable[string] `json:"error_detail,omitempty"`
	InterchangeId  openapi_types.UUID        `json:"interchange_id"`
	MessageSummary MessageSummary            `json:"message_summary"`
	Status         IngestStatus              `json:"status"`
}

// IngestStatus defines model for Ingest.Status.
type IngestStatus string

// InterchangeDetail defines model for interchange-detail.
type InterchangeDetail struct {
	ActiveVersion     ProcessingVersionSummary  `json:"active_version"`
	CreatedAt         time.Time                 `json:"created_at"`
	ErrorDetail       nullable.Nullable[string] `json:"error_detail,omitempty"`
	Id                openapi_types.UUID        `json:"id"`
	MessageSummary    *MessageSummary           `json:"message_summary,omitempty"`
	PreparedAt        time.Time                 `json:"prepared_at"`
	ReceiverId        string                    `json:"receiver_id"`
	ReceiverQualifier *string                   `json:"receiver_qualifier,omitempty"`
	Reference         string                    `json:"reference"`
	SenderId          string                    `json:"sender_id"`
	SenderQualifier   *string                   `json:"sender_qualifier,omitempty"`
	Status            InterchangeDetailStatus   `json:"status"`
}

// InterchangeDetailStatus defines model for InterchangeDetail.Status.
type InterchangeDetailStatus string

// Message defines model for message.
type Message struct {
	CreatedAt           time.Time          `json:"created_at"`
	Id                  openapi_types.UUID `json:"id"`
	InterchangeId       openapi_types.UUID `json:"interchange_id"`
	MessageReference    string             `json:"message_reference"`
	MessageType         string             `json:"message_type"`
	ProcessingVersionId openapi_types.UUID `json:"processing_version_id"`

	// Segments Full parsed segment tree (JSONB)
	Segments       *map[string]interface{}               `json:"segments,omitempty"`
	SubscriptionId nullable.Nullable[openapi_types.UUID] `json:"subscription_id,omitempty"`
}

// MessageList defines model for message-list.
type MessageList struct {
	Items      []Message                 `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor,omitempty"`
	Total      int                       `json:"total"`
}

// MessageSummary defines model for message-summary.
type MessageSummary struct {
	ByType map[string]int `json:"by_type"`
	Total  int            `json:"total"`
}

// ProcessingVersionSummary defines model for processing-version-summary.
type ProcessingVersionSummary struct {
	CreatedAt     time.Time          `json:"created_at"`
	FormatVersion string             `json:"format_version"`
	Id            openapi_types.UUID `json:"id"`
	ParserVersion string             `json:"parser_version"`
	VersionNumber int                `json:"version_number"`
}

// ReprocessFailure defines model for reprocess-failure.
type ReprocessFailure struct {
	InterchangeId openapi_types.UUID `json:"interchange_id"`
	Reason        string             `json:"reason"`
}

// ReprocessFilter At least one filter field should be provided. Omitting all fields matches all interchanges (full corpus reprocessing).
type ReprocessFilter struct {
	// FromDate Reprocess interchanges prepared on or after this date
	FromDate *openapi_types.Date `json:"from_date,omitempty"`

	// InterchangeId Reprocess a single interchange
	InterchangeId *openapi_types.UUID `json:"interchange_id,omitempty"`

	// MessageType Reprocess interchanges containing this message type
	MessageType *string `json:"message_type,omitempty"`

	// SenderId Reprocess all interchanges from this sender
	SenderId *string `json:"sender_id,omitempty"`

	// ToDate Reprocess interchanges prepared on or before this date
	ToDate *openapi_types.Date `json:"to_date,omitempty"`
}

// ReprocessResult defines model for reprocess-result.
type ReprocessResult struct {
	// Failed Number that failed during reprocessing
	Failed   int                 `json:"failed"`
	Failures *[]ReprocessFailure `json:"failures,omitempty"`

	// Matched Number of interchanges matching the filter
	Matched int `json:"matched"`

	// Succeeded Number successfully reprocessed
	Succeeded int `json:"succeeded"`
}

// RollbackRequest defines model for rollback-request.
type RollbackRequest struct {
	// VersionNumber The version number to restore as active
	VersionNumber int `json:"version_number"`
}

// RollbackResponse defines model for rollback-response.
type RollbackResponse struct {
	// ActiveVersionNumber The version number now active after rollback
	ActiveVersionNumber int                `json:"active_version_number"`
	InterchangeId       openapi_types.UUID `json:"interchange_id"`
}

// InterchangeId defines model for InterchangeId.
type InterchangeId = openapi_types.UUID

// BadRequest defines model for bad-request.
type BadRequest = Error

// NotFound defines model for not-found.
type NotFound = Error

// ServerError defines model for server-error.
type ServerError = Error

// IngestFileMultipartBody defines parameters for IngestFile.
type IngestFileMultipartBody struct {
	// File EDIFACT file content. Maximum size: 10 MB (10,485,760 bytes).
	File openapi_types.File `json:"file"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	SubscriptionId      *openapi_types.UUID `form:"subscription_id,omitempty" json:"subscription_id,omitempty"`
	MessageType         *string             `form:"message_type,omitempty" json:"message_type,omitempty"`
	InterchangeId       *openapi_types.UUID `form:"interchange_id,omitempty" json:"interchange_id,omitempty"`
	ProcessingVersionId *openapi_types.UUID `form:"processing_version_id,omitempty" json:"processing_version_id,omitempty"`
	Limit               *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor              *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// IngestFileMultipartRequestBody defines body for IngestFile for multipart/form-data ContentType.
type IngestFileMultipartRequestBody IngestFileMultipartBody

// ReprocessInterchangesJSONRequestBody defines body for ReprocessInterchanges for application/json ContentType.
type ReprocessInterchangesJSONRequestBody = ReprocessFilter

// RollbackVersionJSONRequestBody defines body for RollbackVersion for application/json ContentType.
type RollbackVersionJSONRequestBody = RollbackRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Combined health status
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Ingest an EDIFACT file
	// (POST /interchanges)
	IngestFile(w http.ResponseWriter, r *http.Request)
	// Bulk reprocess interchanges by filter
	// (POST /interchanges/reprocess)
	ReprocessInterchanges(w http.ResponseWriter, r *http.Request)
	// Retrieve an interchange by ID
	// (GET /interchanges/{id})
	GetInterchange(w http.ResponseWriter, r *http.Request, id InterchangeId)
	// Download the original EDIFACT file content
	// (GET /interchanges/{id}/raw)
	GetRawFile(w http.ResponseWriter, r *http.Request, id InterchangeId)
	// Roll back to a previous processing version
	// (POST /interchanges/{id}/rollback)
	RollbackVersion(w http.ResponseWriter, r *http.Request, id InterchangeId)
	// Liveness probe
	// (GET /liveness)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// List parsed messages with filtering
	// (GET /messages)
	ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams)
	// Readiness probe
	// (GET /readiness)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Combined health status
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ingest an EDIFACT file
// (POST /interchanges)
func (_ Unimplemented) IngestFile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bulk reprocess interchanges by filter
// (POST /interchanges/reprocess)
func (_ Unimplemented) ReprocessInterchanges(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve an interchange by ID
// (GET /interchanges/{id})
func (_ Unimplemented) GetInterchange(w http.ResponseWriter, r *http.Request, id InterchangeId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the original EDIFACT file content
// (GET /interchanges/{id}/raw)
func (_ Unimplemented) GetRawFile(w http.ResponseWriter, r *http.Request, id InterchangeId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Roll back to a previous processing version
// (POST /interchanges/{id}/rollback)
func (_ Unimplemented) RollbackVersion(w http.ResponseWriter, r *http.Request, id InterchangeId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /liveness)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List parsed messages with filtering
// (GET /messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readiness)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestFile operation middleware
func (siw *ServerInterfaceWrapper) IngestFile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestFile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReprocessInterchanges operation middleware
func (siw *ServerInterfaceWrapper) ReprocessInterchanges(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReprocessInterchanges(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInterchange operation middleware
func (siw *ServerInterfaceWrapper) GetInterchange(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id InterchangeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInterchange(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRawFile operation middleware
func (siw *ServerInterfaceWrapper) GetRawFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id InterchangeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRawFile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RollbackVersion operation middleware
func (siw *ServerInterfaceWrapper) RollbackVersion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id InterchangeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RollbackVersion(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "subscription_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscription_id", r.URL.Query(), &params.SubscriptionId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subscription_id", Err: err})
		return
	}

	// ------------- Optional query parameter "message_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "message_type", r.URL.Query(), &params.MessageType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "message_type", Err: err})
		return
	}

	// ------------- Optional query parameter "interchange_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "interchange_id", r.URL.Query(), &params.InterchangeId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "interchange_id", Err: err})
		return
	}

	// ------------- Optional query parameter "processing_version_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "processing_version_id", r.URL.Query(), &params.ProcessingVersionId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processing_version_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/interchanges", wrapper.IngestFile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/interchanges/reprocess", wrapper.ReprocessInterchanges)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/interchanges/{id}", wrapper.GetInterchange)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/interchanges/{id}/raw", wrapper.GetRawFile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/interchanges/{id}/rollback", wrapper.RollbackVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/liveness", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readiness", wrapper.GetReadiness)
	})

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type ServerErrorJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type IngestFileRequestObject struct {
	Body *multipart.Reader
}

type IngestFileResponseObject interface {
	VisitIngestFileResponse(w http.ResponseWriter) error
}

type IngestFile200JSONResponse Ingest

func (response IngestFile200JSONResponse) VisitIngestFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IngestFile201JSONResponse Ingest

func (response IngestFile201JSONResponse) VisitIngestFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type IngestFile413JSONResponse Error

func (response IngestFile413JSONResponse) VisitIngestFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type IngestFile422JSONResponse Error

func (response IngestFile422JSONResponse) VisitIngestFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type IngestFile500JSONResponse struct{ ServerErrorJSONResponse }

func (response IngestFile500JSONResponse) VisitIngestFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReprocessInterchangesRequestObject struct {
	Body *ReprocessInterchangesJSONRequestBody
}

type ReprocessInterchangesResponseObject interface {
	VisitReprocessInterchangesResponse(w http.ResponseWriter) error
}

type ReprocessInterchanges200JSONResponse ReprocessResult

func (response ReprocessInterchanges200JSONResponse) VisitReprocessInterchangesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReprocessInterchanges400JSONResponse struct{ BadRequestJSONResponse }

func (response ReprocessInterchanges400JSONResponse) VisitReprocessInterchangesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ReprocessInterchanges500JSONResponse struct{ ServerErrorJSONResponse }

func (response ReprocessInterchanges500JSONResponse) VisitReprocessInterchangesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetInterchangeRequestObject struct {
	Id InterchangeId `json:"id"`
}

type GetInterchangeResponseObject interface {
	VisitGetInterchangeResponse(w http.ResponseWriter) error
}

type GetInterchange200JSONResponse InterchangeDetail

func (response GetInterchange200JSONResponse) VisitGetInterchangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInterchange404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInterchange404JSONResponse) VisitGetInterchangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetInterchange500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetInterchange500JSONResponse) VisitGetInterchangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRawFileRequestObject struct {
	Id InterchangeId `json:"id"`
}

type GetRawFileResponseObject interface {
	VisitGetRawFileResponse(w http.ResponseWriter) error
}

type GetRawFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetRawFile200ApplicationoctetStreamResponse) VisitGetRawFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetRawFile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRawFile404JSONResponse) VisitGetRawFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRawFile500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetRawFile500JSONResponse) VisitGetRawFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RollbackVersionRequestObject struct {
	Id   InterchangeId `json:"id"`
	Body *RollbackVersionJSONRequestBody
}

type RollbackVersionResponseObject interface {
	VisitRollbackVersionResponse(w http.ResponseWriter) error
}

type RollbackVersion200JSONResponse RollbackResponse

func (response RollbackVersion200JSONResponse) VisitRollbackVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RollbackVersion404JSONResponse struct{ NotFoundJSONResponse }

func (response RollbackVersion404JSONResponse) VisitRollbackVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RollbackVersion409JSONResponse Error

func (response RollbackVersion409JSONResponse) VisitRollbackVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RollbackVersion500JSONResponse struct{ ServerErrorJSONResponse }

func (response RollbackVersion500JSONResponse) VisitRollbackVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200Response struct {
}

func (response GetLiveness200Response) VisitGetLivenessResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetLiveness503Response struct {
}

func (response GetLiveness503Response) VisitGetLivenessResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type ListMessagesRequestObject struct {
	Params ListMessagesParams
}

type ListMessagesResponseObject interface {
	VisitListMessagesResponse(w http.ResponseWriter) error
}

type ListMessages200JSONResponse MessageList

func (response ListMessages200JSONResponse) VisitListMessagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMessages400JSONResponse struct{ BadRequestJSONResponse }

func (response ListMessages400JSONResponse) VisitListMessagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListMessages500JSONResponse struct{ ServerErrorJSONResponse }

func (response ListMessages500JSONResponse) VisitListMessagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200Response struct {
}

func (response GetReadiness200Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetReadiness503Response struct {
}

func (response GetReadiness503Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Combined health status
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Ingest an EDIFACT file
	// (POST /interchanges)
	IngestFile(ctx context.Context, request IngestFileRequestObject) (IngestFileResponseObject, error)
	// Bulk reprocess interchanges by filter
	// (POST /interchanges/reprocess)
	ReprocessInterchanges(ctx context.Context, request ReprocessInterchangesRequestObject) (ReprocessInterchangesResponseObject, error)
	// Retrieve an interchange by ID
	// (GET /interchanges/{id})
	GetInterchange(ctx context.Context, request GetInterchangeRequestObject) (GetInterchangeResponseObject, error)
	// Download the original EDIFACT file content
	// (GET /interchanges/{id}/raw)
	GetRawFile(ctx context.Context, request GetRawFileRequestObject) (GetRawFileResponseObject, error)
	// Roll back to a previous processing version
	// (POST /interchanges/{id}/rollback)
	RollbackVersion(ctx context.Context, request RollbackVersionRequestObject) (RollbackVersionResponseObject, error)
	// Liveness probe
	// (GET /liveness)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// List parsed messages with filtering
	// (GET /messages)
	ListMessages(ctx context.Context, request ListMessagesRequestObject) (ListMessagesResponseObject, error)
	// Readiness probe
	// (GET /readiness)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestFile operation middleware
func (sh *strictHandler) IngestFile(w http.ResponseWriter, r *http.Request) {
	var request IngestFileRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestFile(ctx, request.(IngestFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestFileResponseObject); ok {
		if err := validResponse.VisitIngestFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReprocessInterchanges operation middleware
func (sh *strictHandler) ReprocessInterchanges(w http.ResponseWriter, r *http.Request) {
	var request ReprocessInterchangesRequestObject

	var body ReprocessInterchangesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReprocessInterchanges(ctx, request.(ReprocessInterchangesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReprocessInterchanges")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReprocessInterchangesResponseObject); ok {
		if err := validResponse.VisitReprocessInterchangesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInterchange operation middleware
func (sh *strictHandler) GetInterchange(w http.ResponseWriter, r *http.Request, id InterchangeId) {
	var request GetInterchangeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInterchange(ctx, request.(GetInterchangeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInterchange")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInterchangeResponseObject); ok {
		if err := validResponse.VisitGetInterchangeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRawFile operation middleware
func (sh *strictHandler) GetRawFile(w http.ResponseWriter, r *http.Request, id InterchangeId) {
	var request GetRawFileRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRawFile(ctx, request.(GetRawFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRawFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRawFileResponseObject); ok {
		if err := validResponse.VisitGetRawFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RollbackVersion operation middleware
func (sh *strictHandler) RollbackVersion(w http.ResponseWriter, r *http.Request, id InterchangeId) {
	var request RollbackVersionRequestObject

	request.Id = id

	var body RollbackVersionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RollbackVersion(ctx, request.(RollbackVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RollbackVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RollbackVersionResponseObject); ok {
		if err := validResponse.VisitRollbackVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMessages operation middleware
func (sh *strictHandler) ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams) {
	var request ListMessagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMessages(ctx, request.(ListMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMessagesResponseObject); ok {
		if err := validResponse.VisitListMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8Ra3W4bObJ+lQLPubCBliwnnjlnBeyFYzuJdh0745/BYrKBQHWXJI7ZZIdky9EEBvYh",
	"9gn3SRbF/pcoyfmx585Wk8Vi1VdfFYv8wmKdZlqhcpYNv7CMG56iQ+P/GymHJp5zNcNRQj8kaGMjMie0",
	"YsP2Z7i9HZ2yiAn6PeNuziKmeIpsyETCImbwUy4MJmzoTI4Rs/EcU04ip9qk3LEhy3M/0i0zmmWdEWrG",
	"Hh4eaLLNtLLodZrwpEfS0Dr6N9bKofJ/8iyTIuak3MHvljT80lrnfw1O2ZD9z0Gz4YPiqz1AY7Qp1lrd",
	"4YJLkUC5IEx0sgRtoGWmh4gp7XpTnavk6RW6QqtzEyMo7aBY8yFiFs0CTa+Y9eQ63Cr8nGHsMAFBCFBc",
	"QqEBVHMqB3uP1WplRmdonCgcGesE1zH1jsdzobBnkCd8IrEQCX5wxFDlKRt+YK9H52fjm8vL8fnx1Zsz",
	"FrHRxa/H56PT8dnp6PXxyQ2L2Ont+/PRyfHN2fj07Obs5OaM4HlxeTN+fXl7QX+fXF68Ph/5sa+OT8dX",
	"Z7/cnl3feFk3Z1cXx+fjs6uryyv2cQ2TEYu1MSi9VcciEBn/6J00I3qjU5gandYomiNPCDoBwSlay2cB",
	"u7zNU64aq7Q/rsdMO94+sNJ2leg17ZsN6snvGDvSY45cunnAaXOM7+z673d8eucRVXlI35G7vOdDBsy0",
	"dTNTzH3UlIeAktZxl3dEFGovGUF2ZniCxCi5qn7+uMtUpcSo2mfINELNSu7pmsBrPk7QcSHX/fdeZ7nk",
	"FDNaySXcz1FBsRr8FaZcSK+qyqUk/1Y0uWY30VBuCbwd/Fn7fWzzNOVmuSvsy+G9anjQzjRPovM6l8rv",
	"tO2K6lFj7FUNw1avZ/caG3c9wGMnFjheoLGiYLptG82MjtFaoWa9ckZ7z7FB8taYu46RE+6w50SKIUuv",
	"ImC3N5/Lg5nBjJuv3I7BGMUCTQm0zd8/5VyKqUCzYdgUDaoYg18tqmTzEuXX7Qv8IHh6SNbadLfftWB7",
	"Ty0YtyATrWIxBOkW16+Q7Ddg75FQ+g7+2O7HalTx4QvDz5x8QBn9+uTy4jokuYnAyk6P1cniLK1KVp4k",
	"gkiWy/ctKxYR1+Xg17mUVLpZTKCUAM4gwt7fri8vXu2zUI7JJ7WIDdrtCPMQzta4MGyKFbOGfNGB3RaU",
	"9aQIJS3hMO3+8QhmYU0y5sZwzzAKP7txnBtblHo7qc9px2ULSWSRGZp1c3m9qvHbNthix+4eJ8salWGs",
	"rCsRNfj9QrXl5eiEDQ+jCsvDl6Fy5LFbKsZFtV6hTW1JTj+ELopR7VT5rYzi48lslVQhWuXppMPhG51O",
	"K63MWltpbRM7Q8FgadYeJYXcBKj3G/jRILfBje+qf8qJOzQV0hU263LZsQOJ3DrQCqEYBFOBMgE717lM",
	"YIKQGb0QCSZ9uEyFc0LNgEtZDLOQchfP0fqfWrpZ2JsST8baZLmFWhOhZvv9f6qCq1oWo5PNmLC2ruNV",
	"Nbcrv0qloBWdpfmUdHdzYcGLiboQflwW27QwB1JcYluD9gq7kl5FHI/aGB27uVBkZ7+dUgiU5L299tm4",
	"g1X3+KOkl1/MZ0F2/S6XTHCqDX6NTx62gtigzWUg+5S12ZqWFz7kwc25K89GkOS0UAeOjRYt3i4j+/E5",
	"bZ0UAtmtiJXNmupp155+fIGDKjqD2to8jhGTLZL9CGspJJfN7jEJiFvhm0rn9iqBcrjlLy3lhMd37fZa",
	"11/rRN7V+WaOUI4BVfpQg0HrCE7cQlEVUyEjlEipWD/cuY+VRXdoXnQKd50Nv2YHSt+XepdUVa0W9OhX",
	"J5BdWSKs+LoVHvziU131/3jsHVg2YS90qi3cYDxXIuYSTuZcSlRFLbfa85yhpb/BLq3DFKbagFCxTgnQ",
	"ZYOt4jbiEQ/yN2hSrgAlxs6IWDhCKx2EIeXmDl0fjuMYM2cpHNBGRR3uaUiDUIlYiCTnspYbQUY7ts6C",
	"dSaPXU70lHDHI+AqAZtnmTbOVt7CpMMNRaZywvkjSKV0s7Xj96OmxGBDdtgf9AdkC52h4plgQ/ayP+i/",
	"9GWHm3sIHTRNsRm6ILd6jaRYoPLUrUgpnghVEG4s84RsmGBGzK3iJaUMheRh4ZZ95pc3vjE3StiQvUH3",
	"tlhzpQn+YjD4YX3ecleBRu/bsm32ELGfBi+fYcFLhZR+UmKL2kgCLTQtPN9bxjg3wi3Z8MNHYreyLmYn",
	"Op0IQkIxGOqTueMzS8F17QHNPpKQgzZhe77QNuDU66WK50YrnVu5rEBLjq3hSei3+YQqLEzq+CCU9+EK",
	"XW5UMcZXVUUmhL3W4jA6jWAqfBfdKxzVhUO5tX0KsrqSqYDQh1GCaabJIfCff/3by56kwnry0lOgcPws",
	"rK/7SB3YszxFuH573Hvx08/7FJ+1cv5Lqdy9cHOdu0A8ddFZRNNrIbG84EHrXulkuQKUNJdOZNy4A2LC",
	"HoVwFysrNYGQgbqlbVYohffhHf9MWQSs+AOHcDiAd69g73AQHf3/T9H//TyAydKh3e+3y5eJUASWXTTs",
	"tQiTbPcq6+EJI7PsNAcChYwOXBK5LKEYhgnsiQYQhg7EFRr2KYRfDA6fS7NO0VKpRzocHb58+vsprwJ+",
	"ppKnAHcBDAIJSJEKXzIcvXjxTJqUBWyVxbgEf6foF4I97yE1g9uLVwe3F78BqgVKneF+wbqDTWvXoDvo",
	"XP55eqwJsYhQIoJ2/LQIcdTmwHVabIrjzQR5hb2KFVdPKoEqGGIjHBrBIffbjnNjCK4kwtf3uS8O/EHe",
	"n1dB4T00PFQXZ1SUII/nDcfyii6J+woqs2Db9N2H39Do+uBr6ol/oNG9WOfKVTIif8FKDEpmDbFffZLq",
	"2HAbEX47wNbaAc9MRGsnueDNdMtLdQOeMl1V9lAOEFxCdUTzED96DMTbd/4/ICxe5fKuyW5dzE6WrfPa",
	"I6Pki0getlSFBcraGT9Fx4tSliKjPFysg7yodKtioIPPECLfoBt1uhztxxwfwvZqhhx0H3s8fHzSxLZ2",
	"mRd8fNFYrH7qcDQ42u375kHGD0DLFTojkE5/quPEyRL8k5evQcmB4fc7kUKYMPw+glylOhFT0SorfUVT",
	"NEbu0VC1LGZUOsplU4NuwMYVvy9rtWfEhY4dup51BnnaxcfuimydYvg9hArBPwcXp/peSc0T76/KD2H9",
	"vhYkVYNhS9L1LZWyds8wLlASyJPctjlGK6zL+wQluio7V3m4nNaHs1Q4So3VD6QTJmNSCxKdcqEAF1SE",
	"h1Jjqf+vdWP++xH3BEl1td313El1rWkVgnw5qMmo3wb2o8Ffnr7cveFmhjWGINFofRnlT6G+YvMd5XYr",
	"/kfws5YSvI2cBg6ZwYXQuQ0Ew/Y4rNo2O/n5xWAAYurDpi4hqPoVCwy2cM4rwWEwrbwTqtv+YoGtzkt4",
	"VHPXY9A6bjw+tnRIKlVI8Qlu6oxUPbidlqibgOWdxJZahtJlglOeS9eH18VZYOKTVi0YRILK+XceUefu",
	"JILVdok2oSVGp324rvqCxV10b8ItESMndqZFQnx1Lqx7V+15jaz8k9ZPOfocVbZTV18FfM2D1igscuWm",
	"v5G3+yXFJpHrL66+V8lNzxS+W3BxLm8LKsHChi8GEUuLRg8bHg4Guy4PwguUTxO6K3R6jxn/lCMQXn4+",
	"yo3soYp1gkkJpAbirZcO5Y2rnrZ5p+nPXabCAZ1VhbF0xJ1h2ZZesclTltqd5x8Bzi5xD8X3P+c8RvFX",
	"vcupKYXKlPIoVt71lVRVR2pBVnWD/VG87d9dvi8en17/cu4PWH/n0zted+K1ssANAvHpRAo7xyTI6lf1",
	"uo+h9SvfqXO6eCgNzvDpVMQb+f1COyiae3uty4Jc8QUX/l3N/laar3XbwvP1s/GC5brrn+uYS0jQ96L8",
	"O6m9heBwYzhOxd0+i1huJBuyuXPZ8OCAZ6IvqruVfoKLg8Uhe/j48N8AAAD//8a6afJeMAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
